### PR TITLE
implement starknet-rs for contract class endpoints

### LINKED ISSUE #15: Implement `starknet.rs` support for contract class endpoints
Implement autogenerated `starknet.rs` support for the following endpoints.

- `starknet_getClass`
- `starknet_getClassHashAt`
- `starknet_getClassAt`

**Additional Context:**

- https://github.com/NethermindEth/rpc-request-builder/issues/2
- https://github.com/NethermindEth/rpc-request-builder/blob/main/src/api/rpcspec/methods.ts

### PR DESCRIPTION
**Pull request by saimeunt**
Implemented class related starknet methods using the `starknet-rs` package.

Closes #15

### CODE REVIEW

**Comment by saimeunt** [comment]
Following up on this PR, added support for trace endpoints.

Closes #17

Also added initial support for crafting an array of transactions.
Fixed some bugs in the params builder (use structuredClone to deep clone objects instead of performing a shallow copy).

**Comment by saimeunt** [comment]
Since most of the work for #16 was already done on this PR I went along and implemented support for write endpoints.

Closes #16

**Comment by saimeunt** [comment]
Following up on the previous work to support starknet-rs, I've implemented call endpoints.

Closes #18

**Comment by jelilat** [comment]
Can you please create separate PRs for the issues? It'll make it easier to review

@saimeunt

**Comment by saimeunt** [comment]
@jelilat I've created separate PRs for each commit, they will need to be reviewed in order because they depend on each other.

Closing in favor of #30 #31 #32 #33 #34 #35

**Pull request closed without merging**
